export enum ConfigGRPCNameEnum {
  'AUTH' = 'AUTH_MICROSERVICE_GRPC_NAME',
  'USER' = 'USER_MICROSERVICE_GRPC_NAME',
  'LIGHTNOVEL' = 'LIGHTNOVEL_MICROSERVICE_GRPC_NAME',
  'ANIME' = 'ANIME_MICROSERVICE_GRPC_NAME',
  'MANGA' = 'MANGA_MICROSERVICE_GRPC_NAME',
  'NOTIFICATION' = 'NOTIFICATION_MICROSERVICE_GRPC_NAME',
  'RESOURCE' = 'RESOURCE_MICROSERVICE_GRPC_NAME',
  'LOG' = 'LOG_MICROSERVICE_GRPC_NAME',
  'ANALYST' = 'ANALYST_MICROSERVICE_GRPC_NAME',
}
